### ISSUE TITLE
Allow for additional SQL when performing inserts

### ISSUE THREAD

**Issue by jaitaiwan** [jackc/pgxutil#2]
One of the additions to the library I think would be very beneficial is adding a `additionalUnsafeSQL` or `additionalSQL` parameter to the Insert commands.

Use case would be doing things like adding an `ON CONFLICT DO UPDATE` to the command.

I have made a copy and modification in my own library but I get the sense that just adding an extra string concatenation to the `insertSQL` function might not be the best way to accomplish this.

**Comment by jackc** [comment]
I don't know what a good way of handling this would be in the current overall structure. Adding a string to the end of the statement isn't unprecedented -- it's what the `*Returning` variants do. But we already have 8 insert functions. Adding another variant would make it 16. I don't think that approach is scalable.

It would seem going much more advanced than what exists now would require either a data type / struct that represents a query or a builder pattern. Both of which are pretty huge changes ☹️ 

🤷

**Comment by jaitaiwan** [comment]
You’ve already got a query builder inside one of your other libraries at this point haven’t you?

**Comment by jackc** [comment]
> You’ve already got a query builder inside one of your other libraries at this point haven’t you?

Yes, https://github.com/jackc/pgsql, though I haven't done anything with it in quite a while. I've got a bunch of little experimental libraries floating around, like pgxutil itself. A lot of them don't work out.

**Comment by jaitaiwan** [comment]
Do you think it's worth intermixing these two libraries or are you trying to keep them largely independent of one another?

**Comment by jackc** [comment]
🤷 I basically consider these libraries experiments. Occasionally, an idea tried here really works and gets implemented in pgx directly (such as `CollectRows`). I don't have plans for either project. I make changes as need and inspiration strike.

**Comment by jaitaiwan** [comment]
That’s fair, so someone like myself who sees a need and would be keen on contributing, where should I be doing that? Modify the functions here? Integrate the sql builder? Or propose a new function(s) to the main repo ?

**Comment by jackc** [comment]
> That’s fair, so someone like myself who sees a need and would be keen on contributing, where should I be doing that? Modify the functions here? Integrate the sql builder? Or propose a new function(s) to the main repo ?

Probably a fork or a totally new library would be best. Then if you get something that would have wide appeal we can add a link from the pgx README or consider merging the functionality into pgx.
